"""init_product_mgmt_and_arch_mgmt

Revision ID: ef1e7b7db297
Revises: 
Create Date: 2026-02-10 11:09:39.268799

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef1e7b7db297'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_record',
    sa.Column('id', sa.String(length=36), nullable=False, comment='ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='产品名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('product_define', sa.Text(), nullable=True, comment='产品定义，一般为MD文档，描述产品定位、周边关系等'),
    sa.Column('create_user_id', sa.String(length=36), nullable=False, comment='创建人ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_record_create_user_id'), 'product_record', ['create_user_id'], unique=False)
    op.create_index(op.f('ix_product_record_name'), 'product_record', ['name'], unique=False)
    op.create_table('version_record',
    sa.Column('id', sa.String(length=36), nullable=False, comment='ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='版本名称'),
    sa.Column('product_id', sa.String(length=36), nullable=False, comment='所属产品ID'),
    sa.Column('create_user_id', sa.String(length=36), nullable=False, comment='创建人ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['product_id'], ['product_record.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_version_record_create_user_id'), 'version_record', ['create_user_id'], unique=False)
    op.create_index(op.f('ix_version_record_name'), 'version_record', ['name'], unique=False)
    op.create_index(op.f('ix_version_record_product_id'), 'version_record', ['product_id'], unique=False)
    op.create_table('arch_build_artifact',
    sa.Column('id', sa.String(length=36), nullable=False, comment='ID'),
    sa.Column('version_id', sa.String(length=36), nullable=False, comment='版本ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='构建产物名称'),
    sa.Column('artifact_type', sa.String(length=32), nullable=False, comment='产物类型：jar|war|docker_image|binary|npm_package|python_package|library|zip|tar|tar_gz|other'),
    sa.Column('description', sa.Text(), nullable=True, comment='说明'),
    sa.Column('build_command', sa.Text(), nullable=True, comment='构建命令'),
    sa.Column('build_environment', sa.Text(), nullable=True, comment='构建环境信息（OS、编译器版本、运行时版本等）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['version_id'], ['version_record.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_arch_build_artifact_version_type', 'arch_build_artifact', ['version_id', 'artifact_type'], unique=False)
    op.create_index(op.f('ix_arch_build_artifact_artifact_type'), 'arch_build_artifact', ['artifact_type'], unique=False)
    op.create_index(op.f('ix_arch_build_artifact_name'), 'arch_build_artifact', ['name'], unique=False)
    op.create_index(op.f('ix_arch_build_artifact_version_id'), 'arch_build_artifact', ['version_id'], unique=False)
    op.create_table('arch_decision',
    sa.Column('id', sa.String(length=36), nullable=False, comment='ID'),
    sa.Column('version_id', sa.String(length=36), nullable=False, comment='版本ID'),
    sa.Column('adr_number', sa.Integer(), nullable=True, comment='ADR 序号'),
    sa.Column('title', sa.String(length=500), nullable=False, comment='决策标题'),
    sa.Column('status', sa.String(length=24), nullable=False, comment='状态：proposed|accepted|rejected|deprecated|superseded'),
    sa.Column('context', sa.Text(), nullable=True, comment='背景与影响因素'),
    sa.Column('decision', sa.Text(), nullable=True, comment='决策内容'),
    sa.Column('consequences', sa.Text(), nullable=True, comment='后果'),
    sa.Column('alternatives_considered', sa.Text(), nullable=True, comment='已考虑的备选方案'),
    sa.Column('supersedes_id', sa.String(length=36), nullable=True, comment='取代的 ADR ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['supersedes_id'], ['arch_decision.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['version_id'], ['version_record.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_arch_decision_adr_number'), 'arch_decision', ['adr_number'], unique=False)
    op.create_index(op.f('ix_arch_decision_supersedes_id'), 'arch_decision', ['supersedes_id'], unique=False)
    op.create_index(op.f('ix_arch_decision_version_id'), 'arch_decision', ['version_id'], unique=False)
    op.create_index('uq_arch_decision_version_adr_number', 'arch_decision', ['version_id', 'adr_number'], unique=True)
    op.create_table('arch_deployment_unit',
    sa.Column('id', sa.String(length=36), nullable=False, comment='ID'),
    sa.Column('version_id', sa.String(length=36), nullable=False, comment='版本ID'),
    sa.Column('parent_unit_id', sa.String(length=36), nullable=True, comment='父部署单元ID（支持层级关系）'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='部署单元名称'),
    sa.Column('unit_type', sa.String(length=32), nullable=False, comment='单元类型：cluster|node|namespace|pod|container|vm|instance|function|other'),
    sa.Column('description', sa.Text(), nullable=True, comment='说明'),
    sa.Column('deployment_config', sa.Text(), nullable=True, comment='部署配置（JSON）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['parent_unit_id'], ['arch_deployment_unit.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['version_id'], ['version_record.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_arch_deploy_unit_version_type', 'arch_deployment_unit', ['version_id', 'unit_type'], unique=False)
    op.create_index(op.f('ix_arch_deployment_unit_name'), 'arch_deployment_unit', ['name'], unique=False)
    op.create_index(op.f('ix_arch_deployment_unit_parent_unit_id'), 'arch_deployment_unit', ['parent_unit_id'], unique=False)
    op.create_index(op.f('ix_arch_deployment_unit_unit_type'), 'arch_deployment_unit', ['unit_type'], unique=False)
    op.create_index(op.f('ix_arch_deployment_unit_version_id'), 'arch_deployment_unit', ['version_id'], unique=False)
    op.create_table('arch_element',
    sa.Column('id', sa.String(length=36), nullable=False, comment='ID'),
    sa.Column('version_id', sa.String(length=36), nullable=False, comment='版本ID'),
    sa.Column('parent_id', sa.String(length=36), nullable=True, comment='父元素ID'),
    sa.Column('element_type', sa.String(length=32), nullable=False, comment='类型：external_party|external_system|system|subsystem|container|service|microservice|api_service|web_app|batch_job|scheduled_task|database|cache|queue|storage|search_engine|gateway|api_gateway|load_balancer|cdn|function|component|module|library|sdk'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='名称'),
    sa.Column('code', sa.String(length=64), nullable=True, comment='编码/代号'),
    sa.Column('code_repo_url', sa.String(length=500), nullable=True, comment='代码仓地址'),
    sa.Column('code_repo_path', sa.String(length=500), nullable=True, comment='代码仓内相对路径'),
    sa.Column('responsibility', sa.Text(), nullable=True, comment='职责/目的'),
    sa.Column('definition', sa.Text(), nullable=True, comment='详细定义'),
    sa.Column('tech_stack', sa.Text(), nullable=True, comment='技术栈'),
    sa.Column('quality_attributes', sa.Text(), nullable=True, comment='质量属性'),
    sa.Column('constraints', sa.Text(), nullable=True, comment='约束'),
    sa.Column('specifications', sa.Text(), nullable=True, comment='规格'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['parent_id'], ['arch_element.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['version_id'], ['version_record.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_arch_element_version_type', 'arch_element', ['version_id', 'element_type'], unique=False)
    op.create_index(op.f('ix_arch_element_code'), 'arch_element', ['code'], unique=False)
    op.create_index(op.f('ix_arch_element_code_repo_url'), 'arch_element', ['code_repo_url'], unique=False)
    op.create_index(op.f('ix_arch_element_element_type'), 'arch_element', ['element_type'], unique=False)
    op.create_index(op.f('ix_arch_element_name'), 'arch_element', ['name'], unique=False)
    op.create_index(op.f('ix_arch_element_parent_id'), 'arch_element', ['parent_id'], unique=False)
    op.create_index(op.f('ix_arch_element_version_id'), 'arch_element', ['version_id'], unique=False)
    op.create_table('arch_interface',
    sa.Column('id', sa.String(length=36), nullable=False, comment='ID'),
    sa.Column('version_id', sa.String(length=36), nullable=False, comment='版本ID'),
    sa.Column('interface_category', sa.String(length=16), nullable=False, comment='接口类别：logical|physical'),
    sa.Column('parent_id', sa.String(length=36), nullable=True, comment='父接口ID（逻辑接口可分层定义，物理接口的父接口是最底层的逻辑接口）'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='接口名称'),
    sa.Column('code', sa.String(length=64), nullable=True, comment='编码/代号'),
    sa.Column('description', sa.Text(), nullable=True, comment='说明'),
    sa.Column('definition', sa.Text(), nullable=True, comment='功能级定义说明'),
    sa.Column('specification', sa.Text(), nullable=True, comment='规格'),
    sa.Column('constraints', sa.Text(), nullable=True, comment='约束'),
    sa.Column('interface_type', sa.String(length=32), nullable=True, comment='物理接口类型（仅物理接口使用）：rest_api|grpc|message_queue|function_call|rpc|database|file|other'),
    sa.Column('tech_stack', sa.String(length=500), nullable=True, comment='技术栈（仅物理接口使用）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.CheckConstraint("(interface_category = 'logical' AND interface_type IS NULL AND tech_stack IS NULL) OR interface_category = 'physical'", name='chk_interface_category_fields'),
    sa.ForeignKeyConstraint(['parent_id'], ['arch_interface.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['version_id'], ['version_record.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_arch_interface_parent', 'arch_interface', ['parent_id'], unique=False)
    op.create_index('idx_arch_interface_version_category', 'arch_interface', ['version_id', 'interface_category'], unique=False)
    op.create_index(op.f('ix_arch_interface_code'), 'arch_interface', ['code'], unique=False)
    op.create_index(op.f('ix_arch_interface_interface_category'), 'arch_interface', ['interface_category'], unique=False)
    op.create_index(op.f('ix_arch_interface_interface_type'), 'arch_interface', ['interface_type'], unique=False)
    op.create_index(op.f('ix_arch_interface_name'), 'arch_interface', ['name'], unique=False)
    op.create_index(op.f('ix_arch_interface_parent_id'), 'arch_interface', ['parent_id'], unique=False)
    op.create_index(op.f('ix_arch_interface_version_id'), 'arch_interface', ['version_id'], unique=False)
    op.create_table('arch_overview',
    sa.Column('id', sa.String(length=36), nullable=False, comment='ID'),
    sa.Column('version_id', sa.String(length=36), nullable=False, comment='版本ID'),
    sa.Column('section_key', sa.String(length=64), nullable=False, comment='章节键，标准键见 ArchOverviewSectionKey'),
    sa.Column('content', sa.Text(), nullable=True, comment='内容，支持 Markdown'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['version_id'], ['version_record.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_arch_overview_version_id'), 'arch_overview', ['version_id'], unique=False)
    op.create_index('uq_arch_overview_version_section', 'arch_overview', ['version_id', 'section_key'], unique=True)
    op.create_table('arch_artifact_to_artifact',
    sa.Column('id', sa.String(length=36), nullable=False, comment='ID'),
    sa.Column('version_id', sa.String(length=36), nullable=False, comment='版本ID'),
    sa.Column('input_artifact_id', sa.String(length=36), nullable=False, comment='输入构建产物ID'),
    sa.Column('target_artifact_id', sa.String(length=36), nullable=False, comment='目标构建产物ID（由输入产物构建而成）'),
    sa.Column('build_order', sa.Integer(), nullable=False, comment='构建顺序（同一目标产物的多个输入产物）'),
    sa.Column('description', sa.Text(), nullable=True, comment='说明'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['input_artifact_id'], ['arch_build_artifact.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_artifact_id'], ['arch_build_artifact.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['version_record.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_arch_artifact_to_artifact_input', 'arch_artifact_to_artifact', ['input_artifact_id'], unique=False)
    op.create_index('idx_arch_artifact_to_artifact_target', 'arch_artifact_to_artifact', ['target_artifact_id'], unique=False)
    op.create_index('idx_arch_artifact_to_artifact_version', 'arch_artifact_to_artifact', ['version_id'], unique=False)
    op.create_index(op.f('ix_arch_artifact_to_artifact_input_artifact_id'), 'arch_artifact_to_artifact', ['input_artifact_id'], unique=False)
    op.create_index(op.f('ix_arch_artifact_to_artifact_target_artifact_id'), 'arch_artifact_to_artifact', ['target_artifact_id'], unique=False)
    op.create_index(op.f('ix_arch_artifact_to_artifact_version_id'), 'arch_artifact_to_artifact', ['version_id'], unique=False)
    op.create_index('uq_arch_artifact_to_artifact_version_input_target', 'arch_artifact_to_artifact', ['version_id', 'input_artifact_id', 'target_artifact_id'], unique=True)
    op.create_table('arch_artifact_to_deployment',
    sa.Column('id', sa.String(length=36), nullable=False, comment='ID'),
    sa.Column('version_id', sa.String(length=36), nullable=False, comment='版本ID'),
    sa.Column('build_artifact_id', sa.String(length=36), nullable=False, comment='构建产物ID'),
    sa.Column('deployment_unit_id', sa.String(length=36), nullable=False, comment='部署单元ID'),
    sa.Column('deployment_config', sa.Text(), nullable=True, comment='部署配置（JSON，覆盖部署单元的默认配置）'),
    sa.Column('description', sa.Text(), nullable=True, comment='说明'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['build_artifact_id'], ['arch_build_artifact.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deployment_unit_id'], ['arch_deployment_unit.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['version_record.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_arch_artifact_deploy_artifact', 'arch_artifact_to_deployment', ['build_artifact_id'], unique=False)
    op.create_index('idx_arch_artifact_deploy_unit', 'arch_artifact_to_deployment', ['deployment_unit_id'], unique=False)
    op.create_index('idx_arch_artifact_deploy_version', 'arch_artifact_to_deployment', ['version_id'], unique=False)
    op.create_index(op.f('ix_arch_artifact_to_deployment_build_artifact_id'), 'arch_artifact_to_deployment', ['build_artifact_id'], unique=False)
    op.create_index(op.f('ix_arch_artifact_to_deployment_deployment_unit_id'), 'arch_artifact_to_deployment', ['deployment_unit_id'], unique=False)
    op.create_index(op.f('ix_arch_artifact_to_deployment_version_id'), 'arch_artifact_to_deployment', ['version_id'], unique=False)
    op.create_index('uq_arch_artifact_deploy_version_artifact_unit', 'arch_artifact_to_deployment', ['version_id', 'build_artifact_id', 'deployment_unit_id'], unique=True)
    op.create_table('arch_dependency',
    sa.Column('id', sa.String(length=36), nullable=False, comment='ID'),
    sa.Column('version_id', sa.String(length=36), nullable=False, comment='版本ID'),
    sa.Column('source_element_id', sa.String(length=36), nullable=False, comment='源架构元素ID'),
    sa.Column('target_element_id', sa.String(length=36), nullable=False, comment='目标架构元素ID'),
    sa.Column('dependency_type', sa.String(length=48), nullable=True, comment='关系类型：calls|reads_data_from|writes_data_to|depends_on'),
    sa.Column('description', sa.Text(), nullable=True, comment='关系说明'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['source_element_id'], ['arch_element.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_element_id'], ['arch_element.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['version_record.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_arch_dep_element_source_target', 'arch_dependency', ['source_element_id', 'target_element_id'], unique=False)
    op.create_index('idx_arch_dep_version', 'arch_dependency', ['version_id'], unique=False)
    op.create_index('idx_arch_dep_version_source_element', 'arch_dependency', ['version_id', 'source_element_id'], unique=False)
    op.create_index('idx_arch_dep_version_target_element', 'arch_dependency', ['version_id', 'target_element_id'], unique=False)
    op.create_index(op.f('ix_arch_dependency_dependency_type'), 'arch_dependency', ['dependency_type'], unique=False)
    op.create_index(op.f('ix_arch_dependency_source_element_id'), 'arch_dependency', ['source_element_id'], unique=False)
    op.create_index(op.f('ix_arch_dependency_target_element_id'), 'arch_dependency', ['target_element_id'], unique=False)
    op.create_index(op.f('ix_arch_dependency_version_id'), 'arch_dependency', ['version_id'], unique=False)
    op.create_index('uq_arch_dep_version_source_target_type', 'arch_dependency', ['version_id', 'source_element_id', 'target_element_id', 'dependency_type'], unique=True)
    op.create_table('arch_element_interface',
    sa.Column('id', sa.String(length=36), nullable=False, comment='ID'),
    sa.Column('version_id', sa.String(length=36), nullable=False, comment='版本ID'),
    sa.Column('element_id', sa.String(length=36), nullable=False, comment='架构元素ID'),
    sa.Column('interface_id', sa.String(length=36), nullable=False, comment='接口ID'),
    sa.Column('relation_type', sa.String(length=16), nullable=False, comment='关系类型：provides|uses'),
    sa.Column('description', sa.Text(), nullable=True, comment='关系说明'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['element_id'], ['arch_element.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interface_id'], ['arch_interface.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['version_record.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_arch_elem_iface_element', 'arch_element_interface', ['element_id', 'relation_type'], unique=False)
    op.create_index('idx_arch_elem_iface_interface', 'arch_element_interface', ['interface_id', 'relation_type'], unique=False)
    op.create_index('idx_arch_elem_iface_version', 'arch_element_interface', ['version_id'], unique=False)
    op.create_index(op.f('ix_arch_element_interface_element_id'), 'arch_element_interface', ['element_id'], unique=False)
    op.create_index(op.f('ix_arch_element_interface_interface_id'), 'arch_element_interface', ['interface_id'], unique=False)
    op.create_index(op.f('ix_arch_element_interface_relation_type'), 'arch_element_interface', ['relation_type'], unique=False)
    op.create_index(op.f('ix_arch_element_interface_version_id'), 'arch_element_interface', ['version_id'], unique=False)
    op.create_index('uq_arch_elem_iface_version_element_interface', 'arch_element_interface', ['version_id', 'element_id', 'interface_id', 'relation_type'], unique=True)
    op.create_table('arch_element_to_artifact',
    sa.Column('id', sa.String(length=36), nullable=False, comment='ID'),
    sa.Column('version_id', sa.String(length=36), nullable=False, comment='版本ID'),
    sa.Column('element_id', sa.String(length=36), nullable=False, comment='架构元素ID'),
    sa.Column('build_artifact_id', sa.String(length=36), nullable=False, comment='构建产物ID'),
    sa.Column('build_order', sa.Integer(), nullable=False, comment='构建顺序（同一产物的多个元素）'),
    sa.Column('description', sa.Text(), nullable=True, comment='说明'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['build_artifact_id'], ['arch_build_artifact.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['element_id'], ['arch_element.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['version_record.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_arch_element_artifact_build', 'arch_element_to_artifact', ['build_artifact_id'], unique=False)
    op.create_index('idx_arch_element_artifact_element', 'arch_element_to_artifact', ['element_id'], unique=False)
    op.create_index('idx_arch_element_artifact_version', 'arch_element_to_artifact', ['version_id'], unique=False)
    op.create_index(op.f('ix_arch_element_to_artifact_build_artifact_id'), 'arch_element_to_artifact', ['build_artifact_id'], unique=False)
    op.create_index(op.f('ix_arch_element_to_artifact_element_id'), 'arch_element_to_artifact', ['element_id'], unique=False)
    op.create_index(op.f('ix_arch_element_to_artifact_version_id'), 'arch_element_to_artifact', ['version_id'], unique=False)
    op.create_index('uq_arch_element_artifact_version_element_build', 'arch_element_to_artifact', ['version_id', 'element_id', 'build_artifact_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_arch_element_artifact_version_element_build', table_name='arch_element_to_artifact')
    op.drop_index(op.f('ix_arch_element_to_artifact_version_id'), table_name='arch_element_to_artifact')
    op.drop_index(op.f('ix_arch_element_to_artifact_element_id'), table_name='arch_element_to_artifact')
    op.drop_index(op.f('ix_arch_element_to_artifact_build_artifact_id'), table_name='arch_element_to_artifact')
    op.drop_index('idx_arch_element_artifact_version', table_name='arch_element_to_artifact')
    op.drop_index('idx_arch_element_artifact_element', table_name='arch_element_to_artifact')
    op.drop_index('idx_arch_element_artifact_build', table_name='arch_element_to_artifact')
    op.drop_table('arch_element_to_artifact')
    op.drop_index('uq_arch_elem_iface_version_element_interface', table_name='arch_element_interface')
    op.drop_index(op.f('ix_arch_element_interface_version_id'), table_name='arch_element_interface')
    op.drop_index(op.f('ix_arch_element_interface_relation_type'), table_name='arch_element_interface')
    op.drop_index(op.f('ix_arch_element_interface_interface_id'), table_name='arch_element_interface')
    op.drop_index(op.f('ix_arch_element_interface_element_id'), table_name='arch_element_interface')
    op.drop_index('idx_arch_elem_iface_version', table_name='arch_element_interface')
    op.drop_index('idx_arch_elem_iface_interface', table_name='arch_element_interface')
    op.drop_index('idx_arch_elem_iface_element', table_name='arch_element_interface')
    op.drop_table('arch_element_interface')
    op.drop_index('uq_arch_dep_version_source_target_type', table_name='arch_dependency')
    op.drop_index(op.f('ix_arch_dependency_version_id'), table_name='arch_dependency')
    op.drop_index(op.f('ix_arch_dependency_target_element_id'), table_name='arch_dependency')
    op.drop_index(op.f('ix_arch_dependency_source_element_id'), table_name='arch_dependency')
    op.drop_index(op.f('ix_arch_dependency_dependency_type'), table_name='arch_dependency')
    op.drop_index('idx_arch_dep_version_target_element', table_name='arch_dependency')
    op.drop_index('idx_arch_dep_version_source_element', table_name='arch_dependency')
    op.drop_index('idx_arch_dep_version', table_name='arch_dependency')
    op.drop_index('idx_arch_dep_element_source_target', table_name='arch_dependency')
    op.drop_table('arch_dependency')
    op.drop_index('uq_arch_artifact_deploy_version_artifact_unit', table_name='arch_artifact_to_deployment')
    op.drop_index(op.f('ix_arch_artifact_to_deployment_version_id'), table_name='arch_artifact_to_deployment')
    op.drop_index(op.f('ix_arch_artifact_to_deployment_deployment_unit_id'), table_name='arch_artifact_to_deployment')
    op.drop_index(op.f('ix_arch_artifact_to_deployment_build_artifact_id'), table_name='arch_artifact_to_deployment')
    op.drop_index('idx_arch_artifact_deploy_version', table_name='arch_artifact_to_deployment')
    op.drop_index('idx_arch_artifact_deploy_unit', table_name='arch_artifact_to_deployment')
    op.drop_index('idx_arch_artifact_deploy_artifact', table_name='arch_artifact_to_deployment')
    op.drop_table('arch_artifact_to_deployment')
    op.drop_index('uq_arch_artifact_to_artifact_version_input_target', table_name='arch_artifact_to_artifact')
    op.drop_index(op.f('ix_arch_artifact_to_artifact_version_id'), table_name='arch_artifact_to_artifact')
    op.drop_index(op.f('ix_arch_artifact_to_artifact_target_artifact_id'), table_name='arch_artifact_to_artifact')
    op.drop_index(op.f('ix_arch_artifact_to_artifact_input_artifact_id'), table_name='arch_artifact_to_artifact')
    op.drop_index('idx_arch_artifact_to_artifact_version', table_name='arch_artifact_to_artifact')
    op.drop_index('idx_arch_artifact_to_artifact_target', table_name='arch_artifact_to_artifact')
    op.drop_index('idx_arch_artifact_to_artifact_input', table_name='arch_artifact_to_artifact')
    op.drop_table('arch_artifact_to_artifact')
    op.drop_index('uq_arch_overview_version_section', table_name='arch_overview')
    op.drop_index(op.f('ix_arch_overview_version_id'), table_name='arch_overview')
    op.drop_table('arch_overview')
    op.drop_index(op.f('ix_arch_interface_version_id'), table_name='arch_interface')
    op.drop_index(op.f('ix_arch_interface_parent_id'), table_name='arch_interface')
    op.drop_index(op.f('ix_arch_interface_name'), table_name='arch_interface')
    op.drop_index(op.f('ix_arch_interface_interface_type'), table_name='arch_interface')
    op.drop_index(op.f('ix_arch_interface_interface_category'), table_name='arch_interface')
    op.drop_index(op.f('ix_arch_interface_code'), table_name='arch_interface')
    op.drop_index('idx_arch_interface_version_category', table_name='arch_interface')
    op.drop_index('idx_arch_interface_parent', table_name='arch_interface')
    op.drop_table('arch_interface')
    op.drop_index(op.f('ix_arch_element_version_id'), table_name='arch_element')
    op.drop_index(op.f('ix_arch_element_parent_id'), table_name='arch_element')
    op.drop_index(op.f('ix_arch_element_name'), table_name='arch_element')
    op.drop_index(op.f('ix_arch_element_element_type'), table_name='arch_element')
    op.drop_index(op.f('ix_arch_element_code_repo_url'), table_name='arch_element')
    op.drop_index(op.f('ix_arch_element_code'), table_name='arch_element')
    op.drop_index('idx_arch_element_version_type', table_name='arch_element')
    op.drop_table('arch_element')
    op.drop_index(op.f('ix_arch_deployment_unit_version_id'), table_name='arch_deployment_unit')
    op.drop_index(op.f('ix_arch_deployment_unit_unit_type'), table_name='arch_deployment_unit')
    op.drop_index(op.f('ix_arch_deployment_unit_parent_unit_id'), table_name='arch_deployment_unit')
    op.drop_index(op.f('ix_arch_deployment_unit_name'), table_name='arch_deployment_unit')
    op.drop_index('idx_arch_deploy_unit_version_type', table_name='arch_deployment_unit')
    op.drop_table('arch_deployment_unit')
    op.drop_index('uq_arch_decision_version_adr_number', table_name='arch_decision')
    op.drop_index(op.f('ix_arch_decision_version_id'), table_name='arch_decision')
    op.drop_index(op.f('ix_arch_decision_supersedes_id'), table_name='arch_decision')
    op.drop_index(op.f('ix_arch_decision_adr_number'), table_name='arch_decision')
    op.drop_table('arch_decision')
    op.drop_index(op.f('ix_arch_build_artifact_version_id'), table_name='arch_build_artifact')
    op.drop_index(op.f('ix_arch_build_artifact_name'), table_name='arch_build_artifact')
    op.drop_index(op.f('ix_arch_build_artifact_artifact_type'), table_name='arch_build_artifact')
    op.drop_index('idx_arch_build_artifact_version_type', table_name='arch_build_artifact')
    op.drop_table('arch_build_artifact')
    op.drop_index(op.f('ix_version_record_product_id'), table_name='version_record')
    op.drop_index(op.f('ix_version_record_name'), table_name='version_record')
    op.drop_index(op.f('ix_version_record_create_user_id'), table_name='version_record')
    op.drop_table('version_record')
    op.drop_index(op.f('ix_product_record_name'), table_name='product_record')
    op.drop_index(op.f('ix_product_record_create_user_id'), table_name='product_record')
    op.drop_table('product_record')
    # ### end Alembic commands ###
